### PR TITLE
[UI] create route for create asset page /assets/create

### PR DESCRIPTION
**Pull request by gieart87**
the create asset route defined in ui\src\app\app.module.ts like the following codes:

`RouterModule.forRoot([
      {
        path: 'assets/create',
        component: AssetCreateComponent
      }
    ])`

### CODE REVIEW

**Comment by gheemads** [comment]
@suhendra-ep please review

**Comment by suhendra-ep** [comment]
Looks ok for the route, but the unit test still failed, could you please fix it?

**Comment by gieart87** [comment]
@suhendra-ep Basically I don't implement the unit test for UI, could you show me how to reproduce the failed one?

**Comment by gieart87** [comment]
I've fixed the test @suhendra-ep , please check.
asset-test

**Pull request merged**
